spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    sql-script-encoding: utf-8
    platform: postgres
    url: jdbc:log4jdbc:postgresql://db:5432/postgres
    #url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: kw123
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
# show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
