version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: kw123
  db_admin:
    image: dpage/pgadmin4
    depends_on: [db]
    ports: [8080:80]
    environment:
      PGADMIN_DEFAULT_EMAIL: team4@kw.ac.kr
      PGADMIN_DEFAULT_PASSWORD: kw123
  gw:
    image: traefik
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/config.yml"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    ports: [443:443]
    volumes:
      - "./deployments/traefik/certs:/etc/certs:ro"
      - "./deployments/traefik/config.yml:/etc/traefik/config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  whoami_foo:
    image: traefik/whoami
    command: "--name=foo"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami_foo.rule=PathPrefix(`/foo`)"
      - "traefik.http.routers.whoami_foo.entrypoints=websecure"
      - "traefik.http.routers.whoami_foo.tls=true"
  whoami_bar:
    image: traefik/whoami
    command: "--name=bar"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami_bar.rule=PathPrefix(`/bar`)"
      - "traefik.http.routers.whoami_bar.entrypoints=websecure"
      - "traefik.http.routers.whoami_bar.tls=true"
